# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
