# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
