# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The type of the album.
  class AlbumTypeEnum
    ALBUM_TYPE_ENUM = [
      # TODO: Write general description for ALBUM
      ALBUM = 'album'.freeze,

      # TODO: Write general description for SINGLE
      SINGLE = 'single'.freeze,

      # TODO: Write general description for COMPILATION
      COMPILATION = 'compilation'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ALBUM_TYPE_ENUM.include?(value)
    end
  end
end
