# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # CursorPagedArtists Model.
  class CursorPagedArtists < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [CursorPagingSimplifiedArtistObject]
    attr_accessor :artists

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['artists'] = 'artists'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(artists = nil)
      @artists = artists
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      artists = CursorPagingSimplifiedArtistObject.from_hash(hash['artists']) if hash['artists']

      # Create object from extracted values.
      CursorPagedArtists.new(artists)
    end
  end
end
