# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # ExternalUrlObject Model.
  class ExternalUrlObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The [Spotify URL](/documentation/web-api/concepts/spotify-uris-ids) for
    # the object.
    # @return [String]
    attr_accessor :spotify

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['spotify'] = 'spotify'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        spotify
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(spotify = SKIP)
      @spotify = spotify unless spotify == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      spotify = hash.key?('spotify') ? hash['spotify'] : SKIP

      # Create object from extracted values.
      ExternalUrlObject.new(spotify)
    end
  end
end
