# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # FollowersObject Model.
  class FollowersObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # This will always be set to null, as the Web API does not support it at the
    # moment.
    # @return [String]
    attr_accessor :href

    # The total number of followers.
    # @return [Integer]
    attr_accessor :total

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['href'] = 'href'
      @_hash['total'] = 'total'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        href
        total
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        href
      ]
    end

    def initialize(href = SKIP, total = SKIP)
      @href = href unless href == SKIP
      @total = total unless total == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      href = hash.key?('href') ? hash['href'] : SKIP
      total = hash.key?('total') ? hash['total'] : SKIP

      # Create object from extracted values.
      FollowersObject.new(href,
                          total)
    end
  end
end
