# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The ID type: currently only `artist` is supported.
  class ItemType1Enum
    ITEM_TYPE1_ENUM = [
      # TODO: Write general description for ARTIST
      ARTIST = 'artist'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ITEM_TYPE1_ENUM.include?(value)
    end
  end
end
