# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The ID type.
  class ItemType2Enum
    ITEM_TYPE2_ENUM = [
      # TODO: Write general description for ARTIST
      ARTIST = 'artist'.freeze,

      # TODO: Write general description for USER
      USER = 'user'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ITEM_TYPE2_ENUM.include?(value)
    end
  end
end
