# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # LinkedTrackObject Model.
  class LinkedTrackObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Known external URLs for this track.
    # @return [ExternalUrlObject]
    attr_accessor :external_urls

    # A link to the Web API endpoint providing full details of the track.
    # @return [String]
    attr_accessor :href

    # The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the
    # track.
    # @return [String]
    attr_accessor :id

    # The object type: "track".
    # @return [String]
    attr_accessor :type

    # The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for
    # the track.
    # @return [String]
    attr_accessor :uri

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['external_urls'] = 'external_urls'
      @_hash['href'] = 'href'
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash['uri'] = 'uri'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        external_urls
        href
        id
        type
        uri
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(external_urls = SKIP, href = SKIP, id = SKIP, type = SKIP,
                   uri = SKIP)
      @external_urls = external_urls unless external_urls == SKIP
      @href = href unless href == SKIP
      @id = id unless id == SKIP
      @type = type unless type == SKIP
      @uri = uri unless uri == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      external_urls = ExternalUrlObject.from_hash(hash['external_urls']) if hash['external_urls']
      href = hash.key?('href') ? hash['href'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP
      uri = hash.key?('uri') ? hash['uri'] : SKIP

      # Create object from extracted values.
      LinkedTrackObject.new(external_urls,
                            href,
                            id,
                            type,
                            uri)
    end
  end
end
