# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # ManyAudioFeatures Model.
  class ManyAudioFeatures < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[AudioFeaturesObject]]
    attr_accessor :audio_features

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['audio_features'] = 'audio_features'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(audio_features = nil)
      @audio_features = audio_features
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      audio_features = nil
      unless hash['audio_features'].nil?
        audio_features = []
        hash['audio_features'].each do |structure|
          audio_features << (AudioFeaturesObject.from_hash(structure) if structure)
        end
      end

      audio_features = nil unless hash.key?('audio_features')

      # Create object from extracted values.
      ManyAudioFeatures.new(audio_features)
    end
  end
end
