# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # ManyAlbums Model.
  class ManyAlbums < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[AlbumObject]]
    attr_accessor :albums

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['albums'] = 'albums'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(albums = nil)
      @albums = albums
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      albums = nil
      unless hash['albums'].nil?
        albums = []
        hash['albums'].each do |structure|
          albums << (AlbumObject.from_hash(structure) if structure)
        end
      end

      albums = nil unless hash.key?('albums')

      # Create object from extracted values.
      ManyAlbums.new(albums)
    end
  end
end
