# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # ManyAudiobooks Model.
  class ManyAudiobooks < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[AudiobookObject]]
    attr_accessor :audiobooks

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['audiobooks'] = 'audiobooks'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(audiobooks = nil)
      @audiobooks = audiobooks
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      audiobooks = nil
      unless hash['audiobooks'].nil?
        audiobooks = []
        hash['audiobooks'].each do |structure|
          audiobooks << (AudiobookObject.from_hash(structure) if structure)
        end
      end

      audiobooks = nil unless hash.key?('audiobooks')

      # Create object from extracted values.
      ManyAudiobooks.new(audiobooks)
    end
  end
end
