# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # Track1 Model.
  class Track1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Spotify URI
    # @return [String]
    attr_accessor :uri

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['uri'] = 'uri'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        uri
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(uri = SKIP)
      @uri = uri unless uri == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      uri = hash.key?('uri') ? hash['uri'] : SKIP

      # Create object from extracted values.
      Track1.new(uri)
    end
  end
end
