# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class Type8Enum
    TYPE8_ENUM = [
      # TODO: Write general description for EPISODE
      EPISODE = 'episode'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE8_ENUM.include?(value)
    end
  end
end
