# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type: "track".
  class Type3Enum
    TYPE3_ENUM = [
      # TODO: Write general description for TRACK
      TRACK = 'track'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE3_ENUM.include?(value)
    end
  end
end
