# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for ARTIST
      ARTIST = 'artist'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE_ENUM.include?(value)
    end
  end
end
