# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class Type7Enum
    TYPE7_ENUM = [
      # TODO: Write general description for SHOW
      SHOW = 'show'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE7_ENUM.include?(value)
    end
  end
end
