# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class Type6Enum
    TYPE6_ENUM = [
      # TODO: Write general description for AUDIO_FEATURES
      AUDIO_FEATURES = 'audio_features'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE6_ENUM.include?(value)
    end
  end
end
