# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class Type2Enum
    TYPE2_ENUM = [
      # TODO: Write general description for ALBUM
      ALBUM = 'album'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE2_ENUM.include?(value)
    end
  end
end
