# spotify_web_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SpotifyWebApi
  # The object type.
  class Type9Enum
    TYPE9_ENUM = [
      # TODO: Write general description for AUDIOBOOK
      AUDIOBOOK = 'audiobook'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE9_ENUM.include?(value)
    end
  end
end
